title: Rohan Macherla
description: Personal website of Rohan Macherla.
url: "https://rhnmac.com" # change to your actual domain
permalink: /blog/:year/:title/
markdown: kramdown
exclude:
  - README.md
